# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        # isort detecta [tool.isort] en pyproject.toml
        # fuerza a que actúe sobre .py y .pyi (ajusta si usas .pyx, etc.)
        types_or: [python, pyi]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        # black detecta [tool.black] en pyproject.toml
        types_or: [python, pyi]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        # Usa .flake8, setup.cfg o pyproject. Si usas .flake8:
        # args: [--config=.flake8]
        additional_dependencies:
          - flake8-bugbear==24.4.26
